version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8887:8887"
    depends_on:
      - mongo
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  mongodb_data:
    name: mongodb_data
    driver: local